### ISSUE TITLE
Request: Magnet Mandelbrot

### ISSUE THREAD

**Issue by avachon100510** [GBillotey/Fractalshades#130]
Hi! I've long struggled to add the Magnet Mandelbrot in Kalles Fraktaler, so I figured the next best thing to do is to ask if it is possible to have both Types I and II Magnet Mandelbrot in Fractalshades?

These fractals deserve more love and exploration

**Comment by GBillotey** [comment]
Hi! after careful examination I will lack the time to implement this option. The way to implement would be too duplicate the functionality from the `perturbation` module taking into account several critical points. Also I belive some other program may implement this functionality in the future (see https://github.com/5E-324/Imagina)
