### ISSUE TITLE
projection.Expmap

### ISSUE THREAD

**Issue by adammaj1** [GBillotey/Fractalshades#137]
Hi,

Tx for great program 
Can you write more about : 
* "rotates_df : If True, the derivative will be scaled but also rotated according to the mapping."
* screen pixels are defined in [0.5, 0.5]x[-0.5, 0.5]
* the xy_ratio will be udjusted ...
* h_{moy}

TIA

**Comment by GBillotey** [comment]
Hi Adam,

To understand the 'rotate df' option, maybe the best is to play with this example:
https://gbillotey.github.io/Fractalshades-doc/examples/projections/P01-feigenbaum_expmap.html#sphx-glr-examples-projections-p01-feigenbaum-expmap-py
See also the last examples in the movie section (recently added), as it was the main use case and reason to add this option *rotates_df = False*

I believe the pixel windows is now described more clearly also in the doc. In short, all pixels of an image are described by there coordinates, as measured 'on the paper'. See also the paper http://dx.doi.org/10.14236/ewic/EVA2019.74 "At the helm of the Burning ship" which uses a similar concept.

**Comment by adammaj1** [comment]
https://commons.wikimedia.org/wiki/File:Complex_exponential_function_graph_spiral_shape_yvw_dimensions.jpg

Graph of the complex exponential function in y, v, and w dimensions where v+iw = exp(x+iy) for values of x from -1.5 to 1.5 and values of y from -2π to 2π, so that shows two complete rotations of the spiral. Areas checkered with green are for positive values of x. Areas checkered with red are for negative values of x. Areas checkered with yellow are for positive values of y. Areas checkered with blue are for negative values of y.

**Comment by GBillotey** [comment]
I will close this issue for now, feel free to reopen if you still have some question.
