### ISSUE TITLE
Newer version of python/numpy/gmpy breaks the software utterly

### ISSUE THREAD

**Issue by zqh9843** [GBillotey/Fractalshades#157]
Pls update dependency asap and fix compatibility issue.

gmpy2.15 built release only supports python version <3.12 atm

numba version >0.57 deprecated generated_jit used by fractalshades and will output the following warnings:
`ImportError: cannot import name 'generated_jit' from 'numba'`

**Comment by zqh9843** [comment]
https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit

**Comment by zqh9843** [comment]
I install it with python 3.12 on Win platform. It automatically installed all latest dependency packages. I have to fallback to 3.11 and manually replace numba 0.59 with 0.57 for it to operate.

**Comment by zqh9843** [comment]
btw gmpy 2.2 alpha seems to support python 3.12 but I am not sure about its compatibility

**Comment by GBillotey** [comment]
I published bugfix release 1.1.1 which is compatible with numba versions >0.57
For windows users, four versions of python are supported: 3.8, 3.9, 3.10, 3.11 ; they should install automatically from pip as I pushed pre-built binaries to Pypi repository.

For python 3.12, gmpy 2.2 does not seem to ship the binaries - which breaks the build. So supporting 3.12 under windows still needs an upstream change in gmpy.
(If you use python 3.12, you can still install fractalshades in a virtual environment under python 3.11 / through `venv`)

**Comment by GBillotey** [comment]
I will close this issue for now, feel free to reopen if needed.
